language: python

env:
    global:
        - PACKAGE="NeoVintageous"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

matrix:
    allow_failures:
        - python: "3.6"
    fast_finish: true
    include:
        - os: linux
          python: 3.3
        - os: linux
          python: 3.6
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # Enable GUI. See https://docs.travis-ci.com/user/gui-and-headless-browsers.
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install flake8;
            pip install flake8-docstrings;
            pip install python-coveralls;
      elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python3;
            pip3 install flake8;
            pip3 install flake8-docstrings;
            pip3 install python-coveralls;
      fi
    - sh travis.sh bootstrap
    - flake8 --version

script:
    - sh travis.sh run_tests --coverage
    - sh travis.sh run_syntax_tests
    - flake8

after_success:
    - coveralls

notifications:
    email: false
