language: python

env:
    global:
        - PACKAGE="NeoVintageous"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

services:
  - xvfb

matrix:
    include:
        - os: linux
          python: 3.3
          dist: trusty
        - os: linux
          python: 3.8
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # Enable GUI. See https://docs.travis-ci.com/user/gui-and-headless-browsers.
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
                pip install flake8==3.5;
                pip install flake8-docstrings;
                pip install pydocstyle==3.0.0;
                pip install python-coveralls;
                pip install mypy==0.540;
                flake8 --version;
                mypy --version;
            else
                pip install flake8;
                pip install flake8-docstrings;
                pip install pydocstyle;
                pip install python-coveralls;
                pip install mypy;
                flake8 --version;
                mypy --version;
            fi
      fi
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests --coverage
    - sh travis.sh run_syntax_compatibility
    - sh travis.sh run_syntax_tests
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            flake8;
            if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
                mypy ../NeoVintageous || true;
            else
                mypy --show-error-codes ../NeoVintageous || true;
            fi
      fi

after_success:
    - coveralls

notifications:
    email: false
