language: python

env:
    global:
        - PACKAGE="NeoVintageous"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

matrix:
    include:
        - os: linux
          python: 3.3
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install flake8;
            pip install flake8-docstrings;
            pip install python-coveralls;
      elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python3;
            pip3 install flake8;
            pip3 install flake8-docstrings;
            pip3 install python-coveralls;
      fi
    - sh travis.sh bootstrap
    - flake8 --version

script:
    - sh travis.sh run_tests --coverage
    - sh travis.sh run_syntax_tests
    - flake8 --statistics

after_success:
    - coveralls

notifications:
    email: false
