environment:
    global:
        PACKAGE: "NeoVintageous"
        SUBLIME_TEXT_VERSION: "3"

clone_depth: 5

install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: ./appveyor.ps1 "bootstrap" -verbose

build: off

test_script:
    - ps: ./appveyor.ps1 "run_tests" -coverage -verbose
    - ps: ./appveyor.ps1 "run_syntax_tests"
